/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../../mobileapp/app/explore`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/app/stats`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/app/trainer`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/components/animated-icon`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/components/animated-icon.web`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/components/app-tabs`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/components/app-tabs.web`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/components/camera-feed`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/components/camera-feed.web`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/components/hint-row`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/components/web-badge`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/hooks/use-theme`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../../mobileapp/app/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/../../mobileapp/app/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../../mobileapp/app/stats`; params?: Router.UnknownOutputParams; } | { pathname: `/../../mobileapp/app/trainer`; params?: Router.UnknownOutputParams; } | { pathname: `/../../mobileapp/components/animated-icon`; params?: Router.UnknownOutputParams; } | { pathname: `/../../mobileapp/components/animated-icon.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../../mobileapp/components/app-tabs`; params?: Router.UnknownOutputParams; } | { pathname: `/../../mobileapp/components/app-tabs.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../../mobileapp/components/camera-feed`; params?: Router.UnknownOutputParams; } | { pathname: `/../../mobileapp/components/camera-feed.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../../mobileapp/components/hint-row`; params?: Router.UnknownOutputParams; } | { pathname: `/../../mobileapp/components/web-badge`; params?: Router.UnknownOutputParams; } | { pathname: `/../../mobileapp/hooks/use-theme`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../../mobileapp/app/explore${`?${string}` | `#${string}` | ''}` | `/../../mobileapp/app/index${`?${string}` | `#${string}` | ''}` | `/../../mobileapp/app/stats${`?${string}` | `#${string}` | ''}` | `/../../mobileapp/app/trainer${`?${string}` | `#${string}` | ''}` | `/../../mobileapp/components/animated-icon${`?${string}` | `#${string}` | ''}` | `/../../mobileapp/components/animated-icon.web${`?${string}` | `#${string}` | ''}` | `/../../mobileapp/components/app-tabs${`?${string}` | `#${string}` | ''}` | `/../../mobileapp/components/app-tabs.web${`?${string}` | `#${string}` | ''}` | `/../../mobileapp/components/camera-feed${`?${string}` | `#${string}` | ''}` | `/../../mobileapp/components/camera-feed.web${`?${string}` | `#${string}` | ''}` | `/../../mobileapp/components/hint-row${`?${string}` | `#${string}` | ''}` | `/../../mobileapp/components/web-badge${`?${string}` | `#${string}` | ''}` | `/../../mobileapp/hooks/use-theme${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../../mobileapp/app/explore`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/app/stats`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/app/trainer`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/components/animated-icon`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/components/animated-icon.web`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/components/app-tabs`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/components/app-tabs.web`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/components/camera-feed`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/components/camera-feed.web`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/components/hint-row`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/components/web-badge`; params?: Router.UnknownInputParams; } | { pathname: `/../../mobileapp/hooks/use-theme`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
