// GENERATED by scripts/sync-mediapipe-assets.mjs. Do not edit by hand.
//
// Paths are relative to the app's base URL and content-addressed, so they can
// be served immutable. Run `node scripts/sync-mediapipe-assets.mjs` after
// changing the MediaPipe version or a model file, and commit the result.

/** Directory FilesetResolver loads the WASM runtime from. */
export const WASM_BASE_PATH = "mediapipe/wasm-235adcc4";

/** Pose Landmarker bundles. Lite is faster on phones and older laptops; full is more accurate. */
export const POSE_MODEL_PATHS = {
  lite: "models/pose_landmarker_lite.59929e1d.task",
  full: "models/pose_landmarker_full.4eaa5eb7.task",
} as const;
